### ISSUE TITLE
Issue with prd.pe_score() and prd.DeepPrime()

### ISSUE THREAD

**Issue by mathinic** [Goosang-Yu/genet#45]
Hi all,

It seems like the prd.pe_score() function is broken when I install genet on my Ubuntu 22.04 machine. I followed your guidelines and installed CPU only torch.

But when predicting pegRNAs with the following command:
```
seq_wt   = 'ATGACAATAAAAGACAACACCCTTGCCTTGTGGAGTTTTCAAAGCTCCCAGAAACTGAGAAGAAggATAACCTGCAAATGTCAACTGAAACCTTAAAGTGAGTATTTAATTGAGCTGAAGT'
seq_ed   = 'ATGACAATAAAAGACAACACCCTTGCCTTGTGGAGTTTTCAAAGCTCCCAGAAACTGAGACGAAggATAACCTGCAAATGTCAACTGAAACCTTAAAGTGAGTATTTAATTGAGCTGAAGT'
alt_type = 'sub1'
edit_type = 'sub'
edit_len = 1

df_pe = prd.pe_score(seq_wt, seq_ed, alt_type, pe_system='PE2max',cell_type='HEK293T',rtt_max=40)
df_pe.head()
```

I get wrong predictions which are likely also due to wrong spacer length (we get 30bp spacer instead of 20) as you can see in this output:

```
	ID	Target	Spacer	RT-PBS	PBSlen	RTlen	RT-PBSlen	Edit_pos	Edit_len	RHA_len	PE2max_score
0	Sample	ATAAAAGACAACACCCTTGCCTTGTGGAGTTTTCAAAGCTCCCAGA...	ATAAAAGACAACACCCTTGCCTTGTGGAGT	CGTCTCAGTTTCTGGGAGCTTTGAAAACTCCACAAGGCAAGG	7	35	42	34	1	1	0.894857
```

I also tried do use prd.DeepPrime() instead with the following code:
```
pegrna = prd.DeepPrime('Test', seq_wt, seq_ed, edit_type='sub', edit_len=1)
pe2_output = pegrna.predict(pe_system='PE2max', cell_type='HEK293T')
```
--> here the spacer look good (when looking in pegrna.features), but the command pegrna.predict() fails because it can't find a `mean_231124.csv` file.
![image](https://github.com/Goosang-Yu/genet/assets/54500286/23f019f7-98c1-4e7b-a498-443d973f53ce)

Do you have an idea what went wrong here and how I can either fix pe_score or DeepPrime so that the predictions match the website?
Thanks & best wishes,
Nicolas

**Comment by Goosang-Yu** [comment]
Hi Nicolas, 

Thank you for your kind report of some bugs.
I checked genet codes and fixed what you mentioned above (and also issue you sent me by DM). 

These updates were applied from v0.12.0.
Please see [Release note](https://github.com/Goosang-Yu/genet/releases/tag/0.12.0) for more details.

Please remove genet old version and re-install new version.
Can you check whether it works well or not?

Thanks:)

Goosang

**Comment by mathinic** [comment]
Hi Goosang,
Thanks for the quick update! :)
I reinstalled it and the bug of the spacer length is now fixed in both (pe_score and DeepPrime), and they also give the same score. (Score is the same as before the fix, so the spacer length in the dataframe did not seem to have influenced this).

But I checked whether the score I get with pe_score and DeepPrime also matches the website and there seems to be a discrepancy.
If you use the input above and run it on the website (recommended PE2max in HEK293T settings), the pegRNA with PBS length of 7, RT length of 35 and Edit_pos of 34 has a DeepPrime score of **0.6886637**. But in the output of pe_score and DeepPrime  (using the settings above with PE2max and HEK293T) I get a score of **0.894857**.

Which one of those is correct? Is the discrepancy due to my installation or does the genet script in general give slightly different scores than the website?

Best,
Nicolas

**Comment by Goosang-Yu** [comment]
In short, I recommend using GenET. 

The current DeepPrime web tool has not been well-maintained since last year. The most suspicious aspect is that the random seed might not be well set for reproducibility, but I'm not certain. 

When comparing the input you provided as an example (1bp substitution) with GenET and the DeepPrime score on the web server, although they are not exactly the same, they show high reproducibility within the margin of error (see scatter plot below). So, choosing either platform and consistently using it should not be a significant issue.

![DeepPrime_score_genet_vs_web](https://github.com/Goosang-Yu/genet/assets/67215983/495d40ef-c250-4736-9cce-e03f8cbf42bb)

If you have to choose one, I recommend using GenET. GenET is actively maintained, with discovered bugs being fixed, and it receives regular updates. It seems better to use this model. 

The web tool we are managing currently runs on Python code written in November 2022 (before being fully packaged into GenET), and we plan to replace the pipeline with GenET in the near future. The challenge is that the web server is quite outdated, and there's a risk of issues cropping up due to its age, so we've been hesitant to make changes, haha...

Thanks for informing us about important details regarding DeepPrime! If you need more information, feel free to reach out anytime :)

Hope you have a great day today.
Goosang

**Comment by mathinic** [comment]
Perfect, thanks for the clarification! I'll use the genet package then. :)
Best wishes and have a great weekend,
Nicolas
