### ISSUE TITLE
Very long running time, what am I doing wrong?

### ISSUE THREAD

**Issue by francoiskroll** [Goosang-Yu/genet#84]
Thank you for this amazing tool!

After some hurdles with installation (happy to send what finally worked on my M2 macbook), I tried the following example from documentation:

```
from genet.predict import DeepPrimeGuideRNA

target    = 'ATAAAAGACAACACCCTTGCCTTGTGGAGTTTTCAAAGCTCCCAGAAACTGAGAAGAACTATAACCTGCAAATG'
pbs       = 'GGCAAGGGTGT'
rtt       = 'CGTCTCAGTTTCTGGGAGCTTTGAAAACTCCACAA'
edit_len  = 1
edit_pos  = 34
edit_type = 'sub'

pegrna = DeepPrimeGuideRNA('pegRNA_test', target=target, pbs=pbs, rtt=rtt, 
                           edit_len=edit_len, edit_pos=edit_pos, edit_type=edit_type)

pe2max_score = pegrna.predict('PE2max')
```

After 40 min it was still running so I stopped it. The online tool runs in ~ 10 seconds for > 2,000 pegRNAs, so I'm guessing something is wrong, but what?

Thanks for your help!

**Comment by Goosang-Yu** [comment]
Hi @francoiskroll 

Thank you for using Genet. I'm sorry to hear that Genet didn't perform well. When I ran the example you provided on my local server, it didn't take much time except during the import phase. I ran it on a CentOS7 (Linux) server.

![image](https://github.com/Goosang-Yu/genet/assets/67215983/108cf2b6-7452-44a1-b8ee-70c0e4588801)

**1. Did you try genet.predict.DeepPrime and also take too much time?** 
```python
from genet.predict import DeepPrime

seq_wt   = 'ATGACAATAAAAGACAACACCCTTGCCTTGTGGAGTTTTCAAAGCTCCCAGAAACTGAGAAGAACTATAACCTGCAAATGTCAACTGAAACCTTAAAGTGAGTATTTAATTGAGCTGAAGT'
seq_ed   = 'ATGACAATAAAAGACAACACCCTTGCCTTGTGGAGTTTTCAAAGCTCCCAGAAACTGAGACGAACTATAACCTGCAAATGTCAACTGAAACCTTAAAGTGAGTATTTAATTGAGCTGAAGT'

pegrna = DeepPrime('SampleName', seq_wt, seq_ed, edit_type='sub', edit_len=1)

pe2max_output = pegrna.predict(pe_system='PE2max', cell_type='HEK293T')

```
It would be good to check if there are no issues when running the code on an M2 Mac. If there are no problems here, it might be an issue with the DeepPrimeGuideRNA function, so we might need to check the source code.

**2. Which part of the code takes the longest time, pegrna = DeepPrimeGuideRNA() or pegrna.predict?** 
I think the .predict part might take longer... This could be because TensorFlow or Torch isn't running properly.

**3. How about trying to run the SpCas9 function as shown below?** 
Reference results: [genet docs](https://goosang-yu.github.io/genet/1_Predict/2_predict_cas9/#predict-spcas9-activity)
```python
from genet.predict import SpCas9

# Put the whole sequence context that you want to find Cas9 target site.
gene = 'ttcagctctacgtctcctccgagagccgcttcaacaccctggccgagttggttcatcatcattcaacggtggccgacgggctcatcaccacgctccattatccagccccaaagcgcaacaagcccactgtctatggtgtgtcccccaactacgacaagtgggagatggaacgcacggacatcaccatgaagcacaagctgggcgggggccagtacggggaggtgtacgagggcgtgtggaagaaatacagcctgacggtggccgtgaagaccttgaaggtagg'

spcas = SpCas9()
df_out = spcas.search(gene)
```
Since this function only uses TensorFlow, if there are no issues here, we can suspect Torch.

**4. The most suspicious part is the execution of Torch...** 
Could you first check if the device appears as 'cpu' with the code below? I set it to 'cpu' since Mac doesn't support CUDA.
```python
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
```

**5. Or... Were model files downloaded well?**
Please check the models in your environment. When you try DeepPrime with genet first time, it should download checkpoint files (.pt) from github repo (genet-models). Please load models as below.
```python

from genet.models import LoadModel

pe_system = 'PE2max'
cell_type = 'HEK293T'
model_info = LoadModel('DeepPrime', pe_system, cell_type)

model_info.model_dir
```

I would appreciate it if you could check each of the above and provide feedback.

Best, 
Goosang

**Comment by ntfargo** [comment]
If exists: Could you please provide the debug log generated during the execution of your code?

**Comment by francoiskroll** [comment]
Thanks so much for the detailed answer!

I think your code snippet in **1.** fixed everything! So I guess your hypothesis **5.** was the right one.

So first thing I did was running your code in **1.**. I got:

> The model DeepPrime/DP_variant_293T_PE2max_Opti_220428 is not installed. Download checkpoint files.
[Info] File downloaded: [/Users/francoiskroll/miniconda3/envs/deepprime/lib/python3.8/site-packages/genet/models/DeepPrime/DP_variant_293T_PE2max_Opti_220428/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/francoiskroll/miniconda3/envs/deepprime/lib/python3.8/site-packages/genet/models/DeepPrime/DP_variant_293T_PE2max_Opti_220428/__init__.py)
[Info] File downloaded: [/Users/francoiskroll/miniconda3/envs/deepprime/lib/python3.8/site-packages/genet/models/DeepPrime/DP_variant_293T_PE2max_Opti_220428/final_model_0.pt](https://file+.vscode-resource.vscode-cdn.net/Users/francoiskroll/miniconda3/envs/deepprime/lib/python3.8/site-packages/genet/models/DeepPrime/DP_variant_293T_PE2max_Opti_220428/final_model_0.pt)
[... and many more...]

And now my test code above using `DeepPrimeGuideRNA` runs fine!

Snippet **3.** runs fine too, by the way.

Thanks very much.

PS: as minuscule payback, I'll open another issue with how I installed everything, in case it's helpful for future users or to add in the documentation. You're welcome to close it directly!
